### ISSUE TITLE
Make home page accessible through robloxapi.github.io

### ISSUE THREAD

**Issue by PhoenixWhitefire** [RobloxAPI/rbxapiref#14]
I keep typing `robloxapi.github.io` into my address bar and trying random combinations of the `robloxapi` because it just shows up as a 404, forgetting that there needs to be `ref/index.html` at the end for it to even work. Please add a redirect from `robloxapi.github.io` to `robloxapi.github.io/ref/index.html`.

**Comment by Anaminus** [comment]
I've added a [basic landing page](https://robloxapi.github.io/) that links to the main page. In any case, I would recommend bookmarking https://robloxapi.github.io/ref/.
