### ISSUE TITLE
No more updates

### ISSUE THREAD

**Issue by AirtonGamer** [RobloxAPI/rbxapiref#15]
The website seems to be old. the latest version is 609(as January 26 2024) but the website seems to be old and not updated as the last version it has is 605.

**Comment by Anaminus** [comment]
This is caused by Roblox changing the API dump format.

https://twitter.com/MaximumADHD/status/1745134220723286125

**Comment by karl-police** [comment]
> This is caused by Roblox changing the API dump format.
> 
> https://twitter.com/MaximumADHD/status/1745134220723286125

How can I fix it and then test it?

**Comment by karl-police** [comment]
Why is it soooo difficult to update this bruhhhh

![image](https://github.com/RobloxAPI/rbxapiref/assets/12023782/96dcc2cd-d368-4d7c-b4d0-0a8793113c38)


wtf do I need to do, I just wanna import that or something 😐 


The issue is obviously there, but I have nothing to test it with soooo

**Comment by karl-police** [comment]
What does it want from meeee bruuuh
![image](https://github.com/RobloxAPI/rbxapiref/assets/12023782/4ce911c2-22e5-469c-bf8f-57e93b29a3a0)

**Comment by karl-police** [comment]
Nobody wants to do an entire construction place just to fix this. 😐

**Comment by Anaminus** [comment]
Fix by this tool being superseded by https://github.com/RobloxAPI/roar.
