### ISSUE TITLE
Fetch Full API Dump from Roblox Client Tracker instead perhaps

### ISSUE THREAD

**Issue by phoriah** [RobloxAPI/rbxapiref#17]
I noticed *a lot* of data is missing from the API Dump (especially properties with NotScriptable tag)

I suggest fetching from Roblox Client Tracker's [Full-API-Dump](https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/Full-API-Dump.json) instead. 
Or, for better performance you could go with the [Mini](https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/Mini-API-Dump.json) version of it (same data as Full except it's minified).

This would allow me and many other users of your awesome website to easily navigate through many hidden properties and functions that are only available through enough digging (which RCT accomplishes).

@Anaminus

**Comment by Anaminus** [comment]
Fix by this tool being superseded by https://github.com/RobloxAPI/roar, which uses Full-API-Dump.
