### ISSUE TITLE
Make removed members stand out in the search feature

### ISSUE THREAD

**Issue by Kampfkarren** [RobloxAPI/rbxapiref#2]
Example:

I was searching for "gesture", and found `UserInputService.InCameraGesture`. Here's what that looked like on the search.

![image](https://user-images.githubusercontent.com/3190756/65578660-14610080-df2b-11e9-8377-3c0cb33e0750.png)

I click on the link to the developer hub, which was a 404. I then check the page on the ref website, which says it was removed. It doesn't seem like good UX to have removed members look identical to ones that still exist.

**Comment by Anaminus** [comment]
Agreed, but the right appearance doesn't immediately come to mind. I'll have to think about it. For reference:
- Deprecated: strikethrough
- Hidden: reduced opacity
- Unbrowsable: blur

The removed state isn't mutually exclusive with any of these, so the appearance ought to be distinct from them. Then again, some states could be considered more significant than others, and therefore deserve more visibility. Regardless, there are only so many ways to style things before it gets out of hand.

Red is used generally on the site to indicate removal, so it should probably incorporate that somehow. Maybe put the most recent patch next to each search result? Not sure how useful that is generally, but it would at least show the removed state.

Additional things I'd like to do for removed items:
- [ ] Visibility setting
- [ ] Deprioritize in search results
- [ ] No DevHub links, assuming that removed items never have pages

**Comment by Anaminus** [comment]
Couldn't decide on a good visual indicator, but I did implement the three other features. If you find that you still need removed items to have a distinct appearance, just say so.
