### ISSUE TITLE
Double clicking on a member name to copy it also highlights the word "on"

### ISSUE THREAD

**Issue by Quenty** [RobloxAPI/rbxapiref#3]
1. Open up a page with a member
2. Double click on the name to highlight it for copying
3. Expected result: Just member name is highlighted
4. Actual result: Member name, plus the name "On" is highlighted

![image](https://user-images.githubusercontent.com/1774409/66148466-92ca3c00-e5d6-11e9-89ab-27e655f15204.png)

This is annoying, because it makes it slightly harder to copy and paste member names from the api reference into scripts. :p 

Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
OS: Windows 10 Pro

**Comment by Anaminus** [comment]
Resolved by adding `user-select: none` to devhub links, preventing them from being selected.
