### ISSUE TITLE
Concerning the reflection of NotBrowsable

### ISSUE THREAD

**Issue by CloneTrooper1019** [RobloxAPI/rbxapiref#5]
While the blur effect looks cool, I'm a little confused to the purpose of reflecting the NotBrowsable state to users. The applications its used in seem to be arbitrary and pointless, and the Object Browser has been given very little attention since its introduction. 

The ReflectionMetadata in general seems to be a bit flaky at this stage, and I'm split on whether we should be manually adjusting some of its data or just ignoring most of it all together.

Any thoughts on this?

**Comment by Anaminus** [comment]
I agree that decorating NotBrowsable is excessive (apparently it's also barely legible in not-Firefox), but I think there's still value in having a visibility setting.

I'm not interested in manually augmenting metadata. Save documentation, the scope of rbxapiref is that it deals only with what is provided by Roblox. In the long run, it's easier and more beneficial to push for such changes upstream.
