### ISSUE TITLE
Settings file unavailable

### ISSUE THREAD

**Issue by Raviates** [RobloxAPI/rbxapiref#7]
After running "go build" with Go 13.8, upon execution of the program:
 
open settings file: open C:\Users\Name\AppData\Roaming\rbxapiref\settings.json: The system cannot find the path specified.

C:\Users\Name\AppData\Roaming\rbxapiref\ does not exist.

Windows 10.

**Comment by Raviates** [comment]
Quick fix appears to be making an empty settings.json (empty as in "{}", truly empty will trigger EOF error) and using the \settings option.

**Comment by Anaminus** [comment]
Fixed by 0b1f86e73c120d69283964adb8614929323f1a3a.
