### ISSUE TITLE
Links in generated documentation incorrect, are absolute

### ISSUE THREAD

**Issue by Raviates** [RobloxAPI/rbxapiref#9]
In the generated documentation, the links all point to "/ref/" at the start, which seems to be incorrect because they are absolute and not relative, and that there isn't a ref directory in the directory the files are in because they are nested inside of it. Most links could replace "/ref/" with "../" possibly?

This goes for all links such as hyperlinks and CSS / JavaScript imports.

I am on Windows 10.

**Comment by Anaminus** [comment]
The generated website needs to be served by an HTTP server for it to work correctly. The following program can be used to run a simple file server:

```go
package main

import (
	"log"
	"net/http"
)

func main() {
	// Note: parent of \ref directory.
	directory := `C:\path\to\robloxapi.github.io`
	log.Fatal(http.ListenAndServe(":8080", http.FileServer(http.Dir(directory))))
}
```

This will serve the website at http://localhost:8080/ref/.

Eventually this will be built in to rbxapiref itself.
